### ISSUE TITLE
Scalameter 0.8 SNAPSHOT

### ISSUE THREAD

**Issue by sirinath** [reactors-io/reactors#45]
Can you ensure scalameter 0.8 SNAPSHOT is published or depend on 0.7

**Comment by sirinath** [comment]
Realised though they are not on Central they can be found in Sonatype

**Comment by axel22** [comment]
Indeed they can. However, the stable version should not depend on any snapshots, and this particular dependency should only exist for tests. I will publish a new major version.

**Comment by axel22** [comment]
Note: the 0.6.1 version should have the correct dependencies, and not depend on ScalaMeter snapshot in the main configuration.
