### ISSUE TITLE
Issue with zip schematics vs sync schematics 

### ISSUE THREAD

**Issue by sirinath** [reactors-io/reactors#46]
`((in._1 zip in._2)((_, _)) zip in._3)((p1, p2) => f(p1._1, p1._2, p2))` does not seem to work as zip does not seem to produce a tuple, `((in._1 sync in._2)((_, _)) sync in._3)((p1, p2) => f(p1._1, p1._2, p2))` works

**Comment by axel22** [comment]
Can you be more specific - is the problem that the `zip` snippet does not compile for you? Or it does not produce the value you expect?

**Comment by axel22** [comment]
This should work:

```
test("triple zip") {
    val e1 = new Events.Emitter[String]
    val e2 = new Events.Emitter[String]
    val e3 = new Events.Emitter[String]
    val s1 = e1.toSignal("")
    val s2 = e2.toSignal("")
    val s3 = e3.toSignal("")
    val buffer = mutable.Buffer[(String, String, String)]()
    val f = (x: String, y: String, z: String) => (x, y, z)
    val zipped = ((s1 zip s2)((_, _)).toSignal(("", "")) zip s3) {
      (p1, p2) => f(p1._1, p1._2, p2)
    }
    val sub = zipped.onEvent(buffer += _)
    e1 react "a"
    e2 react "b"
    e3 react "c"
    val expected = Seq(
      ("a", "", ""),
      ("a", "b", ""),
      ("a", "b", "c")
    )
    assert(buffer == expected)
  }
```

Since `zip` does not buffer values into order to pair them, but instead must reuse the previous value, its result must be converted to a `Signal` in order to be used again. The `toSignal` combinator converts an event stream to a signal with an initial value.

**Comment by axel22** [comment]
But, in retrospect, it seems there is no reason no to make the result of a `zip` a `Signal`.

**Comment by sirinath** [comment]
I think zip and synch should be Signals as working with them in the current form is very difficult and verbose. Also synch and zip n would be great.

**Comment by axel22** [comment]
Ok, `zip` should be fixed now. I'd like to retain a version of `sync` that also works only on event streams (if I just make `sync` return a `Signal`, then the inputs for `sync` should also be `Signal`s, and then I cannot call `sync` on event streams any more).

How about we call the `Signal` version `syncSig`?

With N-elements version of `sync`, do you expect to get a `Seq[Signal[T]]` as an input?

**Comment by sirinath** [comment]
Yes `Seq`.

For API consistency perhaps retain the old `zip` and `zipSig`?

**Comment by axel22** [comment]
Ok. Btw, there is an `aggregate` method on the `Signal` object that folds - if your function `f` is associative, and the output type is the same as the input type, then you can use that already.

I will also add `zip` and `sync` there, which will not assume the same return type, and will not have to be associative (but will have to fold over the entire sequence of input signals).

**Comment by sirinath** [comment]
Currently what I am facing is how to deal with large number of signals and look across them do operations like generating cov matrices etc. That's why I need sync many items. Also for this you need to keep n history and do it very efficiently as you have very small time (in some cases as small as a few micro seconds) to respond.

**Comment by axel22** [comment]
Sounds like you need a `zip` of many signals then. If you need high performance, make sure you don't allocate any objects (such as boxed primitives or sequences of elements). The `Events#mutate` combinator can help you there - it allows an event stream to modify a mutable value (wrapped into an `Events.Mutable` object, which is itself an event stream of modifications) each time an event arrives. The mutable value could be a covariance matrix, and the event stream that modifies it could represent changes in the input dataset.

**Comment by sirinath** [comment]
I need a zip and sync for a large number of items.
