### ISSUE TITLE
Ability to look back n items and / or having moving windows

### ISSUE THREAD

**Issue by sirinath** [reactors-io/reactors#48]
There are many times where you need n items of history. So like batch is it possible to have a moving window.

**Comment by axel22** [comment]
I will add support for a sliding window using the immutable `Conc` tree collection (from the `reactors-common` module, which you should have if you depend on the `reactors-core` package).

Note, however, that if you need sliding windows, it is very likely that using the `mutate` combinator to modify a mutable `ConcBuffer` collection is more efficient than using an immutable `Conc`. The mutable `ConcBuffer` allows appending elements very efficiently. I will modify it to also support efficient `pushLeft`, `pushRight`, `popLeft` and `popRight`.
