### ISSUE TITLE
Collections++

### ISSUE THREAD

**Issue by sirinath** [reactors-io/reactors#49]
Current collection cover many cases but the following might be desirable.

Have the following in traits:

 - update
 - insert
 - delete

So depending on the traits you mixin you get the events do not incur cost of having events you might not need.

Also the following collections might be also desirable:

 - Queues (Bounded, Unbounded)
 - Priority Queues
 - MultiMaps (maybe using nesting of another collection type)
 - Sets (ordered, unordered)
 - Lists
 - Map (ordered, unordered)
 - Stacks
 - Tensors, matrices (perhaps with interop with or backed by http://nd4j.org/scala.html, https://github.com/scalanlp/breeze)

Performance at least good as

 - https://koloboke.com/
 - http://fastutil.di.unimi.it/

**Comment by axel22** [comment]
Why not use those existing libraries (e.g. Breeze) if you need very fast collections?

**Comment by sirinath** [comment]
Since you already have some data structures I was thinking of using them. Any way other collections are not reactive where you can listen to changes.

**Comment by axel22** [comment]
Speaking of priority queues, there already a `BinaryHeap`, and an `RBinaryHeap` version of that class. For maps, there are `RHashMap` and `RFlatHashMap` classes. For a special, memory-friendly, yet fast-to-index encoding of matrices, there is the `HashMatrix` class (and alternatively `QuadMatrix`, which is slightly slower, but allows some additional operations). For sets, there is `RHashSet`. For queues, there is the `UnrolledRing` class, which has fast O(1) enqueue/dequeue, but O(n) index. There is also the `ConcBuffer` with O(log n) index, and fast O(1) appends.

All these can be found in the `reactors-container` module.

Can you tell me:

- Exactly which collections classes you're looking for?
- If you need them to be reactive, and for what purpose?

**Comment by sirinath** [comment]
I have been playing around with `RHashMap`. There are times I wanted more finer control of the events. I am not interested in the 1st insert but I am interested on the 1st update if there is a mapping. There maybe times I am interested in inserts and deletes only but not updates. I can listed to the relevant events on the data structure and trigger calculations.

Also I have been wanting to fixed size window (wounded queue) when a new value is appended I like to know the corresponding key. This is what I had in mind for MultiMaps using bounded queue. My use case is if I get an ungrouped stream of prices I want to group it and window it to calculate signals per asset but restricted to a universe. So when the window is full and new items come I want to trigger calculations of signals. When dealing with signals since they are already again I am interested only in updates. In short when a nested data structure is updated I want to know where in the outer data structures this item resides in. I still have not to using the new window functionality and perhaps this might solve everything. 

Through I have not started using or exploring or using HashMatrix cell / range updates can trigger other updates akin to Excel.

**Comment by sirinath** [comment]
In high level perspective how I am looking at Reactive Data Structures model like the following: data changes then you react and do some calculation which you save into a data structure, this data change triggers computation which updates data in another data structure, this data change triggers computation ... and the cycle continues until the data is outputted. Am I in the right track here?

**Comment by axel22** [comment]
Yes, that's a good summary of how reactive data structures work!

Ok, thanks for explaining your use-case! It sounds like you need additional event streams on reactive maps. I've extended the framework with additional combinators that should satisfy your use-case. In particular, there are `adds` and `updates` event streams on reactive maps now (implemented in terms of the `modified` event stream), which will give you information about the first insertion of the key, and information about subsequent insertions.

Along with the `sliding` functionality, you should be able to track windows of prices for particular assets (it also seems to me that `groupBy` and `sliding` on event streams should be sufficient to achieve what you're after, even without reactive maps).

**Comment by sirinath** [comment]
In addition I think I will need as associative n item zip and sync
