### ISSUE TITLE
RCell with a Mutating Reference Trait

### ISSUE THREAD

**Issue by sirinath** [reactors-io/reactors#52]
To avoid GC I have some pooled objects which can copy state from another object. I want a way to have a RCell which will hold such an object and I want to map assignment (:=) to map to this functionality while other functionality like events RCell stay the same.

Event notification and := function may need synchonisation perhaps using something like https://github.com/LMAX-Exchange/disruptor-proxy

**Comment by axel22** [comment]
Could you post a concise snippet of code demonstrating what you would like to achieve?

In almost all cases, you should avoid synchronization, and rely on reactor instances to achieve concurrent execution.

**Comment by sirinath** [comment]
A code snippet may not convey the message. Let me better explain it.

I have marix assigned to RCell. Row of data changes. Now I need assignments which will copy the underlying data structure to the updated matrix. This functionality is there but if I use `:=` function each update I have to create a new very large object where at most I can have GC only once a day.

**Comment by axel22** [comment]
Can you, for example, do the following:

```
class RMatrix(private val rawMatrix: YourMatrixClass) {
  private var subscription: Subscription = Subscription.empty
  private val updates = new Event.Emitter[XY]

  def apply(x: Int, y: Int): Double = rawMatrix.get(x, y)

  def update(x: Int, y: Int, d: Double): Unit = {
    rawMatrix.set(x, y, d)
    updates.react(XY(x, y))
  }

  def incrementalCopy: RMatrix = {
    val m = new RMatrix
    m.subscription = updates.onEvent { xy =>
      m(xy.x, xy.y) = this(xy.x, xy.y)
    }
    m
  }
}
```

**Comment by sirinath** [comment]
If I use RMatrix I cannot have the operations in Breeze or ND4J so I have to sometimes use them.

**Comment by cantor-chron** [comment]
Why not have Breeze operations on the `RMatrix` class?

```
class RMatrix(private val rawMatrix: BreezeMatrix) {
  private var subscription: Subscription = Subscription.empty
  private val updates = new Event.Emitter[XY]
  private val breezeOperations = new Event.Emitter[BreezeArgType]

  def apply(x: Int, y: Int): Double = rawMatrix.get(x, y)

  def update(x: Int, y: Int, d: Double): Unit = {
    rawMatrix.set(x, y, d)
    updates.react(XY(x, y))
  }

  def someBreezeOperation(arg: BreezeArgType): Unit = {
    rawMatrix.breezeOperation(arg)
    breezeOperations.react(arg)
  }

  def incrementalCopy: RMatrix = {
    val m = new RMatrix(BreezeMatrix.copy(rawMatrix))
    m.subscription = new Subscription.Composite(
      updates.onEvent { xy =>
        m(xy.x, xy.y) = this(xy.x, xy.y)
      },
      breezeOperations.onEvent { arg =>
        rawMatrix.breezeOperation(arg)
      }
    }
    m
  }
}
```

**Comment by sirinath** [comment]
OK. Is it too much trouble to have it backed by either [nd4s](https://github.com/deeplearning4j/nd4s) and [breeze](https://github.com/scalanlp/breeze)

**Comment by cantor-chron** [comment]
If the above snippet meets your needs, then there should be no need to introduce a dependency on either nd4s or breeze in Reactors.IO. It seems to me that you should, in your application, add a library dependency on nd4s, breeze and Reactors.IO, and then create an `RMatrix` class like the one shown above.

Is there any specific reason why the proposed solution does not work for you?

**Comment by sirinath** [comment]
My bad. I did not fully understand you meant. This seems pretty straightforward. There are few things I am not sure not to get about. 

1. I do not want RMetrix being tied to a particular matrix type should be able to change it.
2. If the JIT does not inline the raw matix there is 2 referencing operations which I want to avoid.
3. I would like to avoid to having define and delegate to all the underlying classes operations.

**Comment by cantor-chron** [comment]
No problem! I would suggest the following:

> I do not want RMatrix being tied to a particular matrix type should be able to change it. Better still if it can be any data structure.

In this case, you should create a class that is parametric in the underlying matrix:

```
trait Matrix {
  def apply(x: Int, y: Int): Double
  def update(x: Int, y: Int, v: Double): Unit
}

class BreezeMatrix(val m: breeze.Matrix) {
  // ... implementation of the methods ...
}

class ND4SMatrix(val m: nd4s.Matrix) {
  // ... ditto ...
}

class RMatrix(private val rawMatrix: Matrix) {
  private var subscription: Subscription = Subscription.empty
  private val updates = new Event.Emitter[XY]
  private val breezeOperations = new Event.Emitter[BreezeArgType]

  def apply(x: Int, y: Int): Double = rawMatrix.get(x, y)

  def update(x: Int, y: Int, d: Double): Unit = {
    rawMatrix.set(x, y, d)
    updates.react(XY(x, y))
  }

  def someBreezeOperation(arg: BreezeArgType): Unit = {
    rawMatrix.breezeOperation(arg)
    breezeOperations.react(arg)
  }

  def incrementalCopy: RMatrix = {
    val m = new RMatrix(BreezeMatrix.copy(rawMatrix))
    m.subscription = new Subscription.Composite(
      updates.onEvent { xy =>
        m(xy.x, xy.y) = this(xy.x, xy.y)
      },
      breezeOperations.onEvent { arg =>
        rawMatrix.breezeOperation(arg)
      }
    }
    m
  }
}
```

> If the JIT does not inline the raw matrix there is 2 referencing operations which I want to avoid.

It is very unlikely that this is a problem. JVM optimizing compilers are usually very aggressive at inlining methods, that's the core prerequisite for their optimizations.

> I would like to avoid to having define and delegate to all the underlying classes operations. This will get out of hand when there more than one data structures and also lot of re working when new version of the library comes out. So like in (1) it should be injected but behave like the underlying structure.

This could be regarded as a kind of aspect-oriented programming - you want to mimic the interface. In static languages, this is typically done using compile-time metaprogramming - in the case of Scala, macros. You could create a [macro](http://docs.scala-lang.org/overviews/macros/overview.html) that generates the operations for you.

In your case, it seems cheaper to just implement the methods that you need.

**Comment by sirinath** [comment]
OK. Thanks.
