### ISSUE TITLE
Missing package: com.storm-enroute#coroutines_2.11;0.8

### ISSUE THREAD

**Issue by jsancio** [reactors-io/reactors#62]
```
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/storm-enroute/coroutines_2.11/0.8-SNAPSHOT/coroutines_2.11-0.8-SNAPSHOT.pom
[info] Resolving jline#jline;2.12.1 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.storm-enroute#coroutines_2.11;0.8-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.storm-enroute:coroutines_2.11:0.8-SNAPSHOT
[warn]            +- io.reactors:reactors-extra_2.11:0.7 (.../build.sbt#L6)
[warn]            +- io.reactors:reactors_2.11:0.7 (.../build.sbt#L6)
```

Do we expect users to use publish Maven artifacts? Or do we want user to build snapshots build? If so please document how to do so. Thanks!

**Comment by cantor-chron** [comment]
No, dependency from the all-in-one Reactors bundle on Coroutines was by mistake. Until Coroutines is reimplemented with Scala Meta, we will remove it from as a dependency.

I will publish the 0.8 version of Reactors now.

**Comment by cantor-chron** [comment]
Btw, until I publish 0.8, you can use the individual artifacts:

https://mvnrepository.com/artifact/io.reactors/reactors-common_2.11
https://mvnrepository.com/artifact/io.reactors/reactors-core_2.11
https://mvnrepository.com/artifact/io.reactors/reactors-container_2.11
https://mvnrepository.com/artifact/io.reactors/reactors-remote_2.11

**Comment by cantor-chron** [comment]
0.8 was released on Sonatype, and Maven should be synced in a few hours.
