### ISSUE TITLE
Can't find createEventStream

### ISSUE THREAD

**Issue by martez81** [reactors-io/reactors#68]
I'm following tutorial on page http://reactors.io/tutorialdocs//reactors/event-streams/index.html

Following line does not work.
`val myEvents: Events[String] = createEventStream()`

`createEventStream` does not seem to be in the scope when importing `import io.reactors._`

I'm using reactors 0.9-SNAPSHOT in SBT console.

**Comment by axel22** [comment]
Hi,

Sorry for the confusion - in that example, `createEventStream` is meant to be some user-defined function that creates an event stream object. I will update the example to include the definition of the `createEventStream` function.

**Comment by martez81** [comment]
Thanks!
So in this case `createEventStream` could be something like `new Events.Emitter[String]` ?

**Comment by axel22** [comment]
Yes, exactly!

**Comment by axel22** [comment]
Fixed in: https://github.com/reactors-io/reactors/commit/6d6f7b0b7386036b10737abca3496aae8d9ab2ba
